CREATE DATABASE RENTAL_PROJECT;
GO

USE RENTAL_PROJECT;
GO

CREATE TABLE EMPRESA(
	idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(20),
	endereco VARCHAR(150)
);
GO

CREATE TABLE VEICULO(
	idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	cor VARCHAR(15) NOT NULL,
	placa VARCHAR(8) NOT NULL
);
GO

CREATE TABLE CLIENTE(
	idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	nome VARCHAR(10) NOT NULL,
	sobrenome VARCHAR(10),
	RG VARCHAR(12) NOT NULL
);
GO

CREATE TABLE ALUGUEL(
	idAluguel INT PRIMARY KEY IDENTITY(1,1),
	idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
	idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	preco SMALLMONEY NOT NULL,
	Adata DATE 
);
GO